# Generated by Django 4.1.5 on 2023-02-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_tax_tax_alter_product_discount_alter_product_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
