# Generated by Django 4.1.5 on 2023-02-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_ht',
            new_name='price',
        ),
    ]
