# Generated by Django 4.1.5 on 2023-03-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
