# Generated by Django 4.1.5 on 2023-02-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0007_alter_newuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
