# Generated by Django 4.1.5 on 2023-03-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_shippingaddress_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stripe_token',
        ),
    ]
