# Generated by Django 4.1.5 on 2023-03-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
