# Generated by Django 4.1.5 on 2023-03-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_cartitem_customer'),
        ('order', '0014_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='items', to='product.cartitem'),
        ),
    ]
